In [38]:


from datetime import date
from typing import Dict, Self
from sqlmodel import SQLModel, Field
from sqlalchemy.types import String
from pydantic import HttpUrl
from pathlib import Path

# Assume MEDIUM_HOSTS and logger are defined elsewhere

class InputContent(SQLModel, table=True):
	id: int | None = Field(default=None, primary_key=True)  # Add an ID as primary key
	source: HttpUrl | Path = Field(unique=True, sa_type=String(2048))
	upload_date: date
	already_read: bool = Field(default=False)
	read_priority: int = Field(default=1, ge=0, le=5)
	provenance: str | None = Field(default=None)  # Use Optional for clarity

/Users/tdurouchoux/opt/anaconda3/envs/py311_dsview/lib/python3.11/site-packages/sqlmodel/main.py:638: SAWarning: This declarative base already contains a class with the same class name and module name as __main__.InputContent, and will be replaced in the string-lookup table.
  DeclarativeMeta.__init__(cls, classname, bases, dict_, **kw)

InvalidRequestError: Table 'inputcontent' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.

In [3]:
from typing import List

In [4]:
tags = ["ML", "DL"]

In [36]:
content = InputContent(source="https://towardsdatascience.com/automated-detection-of-data-quality-issues-54a3cb283a91", upload_date=date.today())

In [37]:
content.source

'https://towardsdatascience.com/automated-detection-of-data-quality-issues-54a3cb283a91'

In [34]:
valid_content = InputContent.model_validate(content)

In [35]:
valid_content.source

'https://towardsdatascience.com/automated-detection-of-data-quality-issues-54a3cb283a91'

In [7]:
type(content.link)

pydantic_core._pydantic_core.Url

In [4]:
type(content.link)

str

In [13]:
from datetime import date
import logging
from pathlib import Path
from typing import Dict, Union

from pydantic import BaseModel, Field, HttpUrl

MEDIUM_HOSTS = ["medium.com", "towardsdatascience.com"]

logger = logging.getLogger(__name__)


class InputContent(BaseModel):
    link: Union[HttpUrl, Path]
    upload_date: date
    already_read: bool = False
    read_priority: int = Field(default=1, ge=0, le=5)
    source: str = None

    def model_post_init(self, __context):
        try:
            if self.link.host in MEDIUM_HOSTS:
                logger.info("Received a medium link, redirecting to readmedium")
                self.link = HttpUrl("https://readmedium.com/" + str(self.link))

        except AttributeError:
            return

    def get_str_dict(self) -> Dict:
        instance_dict = dict(self)
        instance_dict["link"] = str(self.link)
        instance_dict["upload_date"] = self.upload_date.isoformat()

        if self.source is None:
            del instance_dict["source"]

        return instance_dict

In [39]:
import pandas as pd

In [40]:
pdf_snapshot = pd.read_json("../snapshot_content.json")

In [43]:
pdf_snapshot.head(30)

,already_read,link,read_priority,upload_date,source
0,False,https://abseil.io/resources/swe-book,1,2023-01-19,NaN
1,False,https://inseefrlab.github.io/formation-mlops/s...,1,2023-10-05,NaN
2,False,https://codelabs.developers.google.com/tensorf...,1,2023-09-21,NaN
3,False,https://stanford-cs329s.github.io/,1,2022-09-15,NaN
4,True,https://github.com/anthropics/courses/tree/mas...,4,2024-09-29,Aucune
5,False,https://carl-mcbride-ellis.github.io/TOBoML/TO...,1,2024-07-10,NaN
6,True,https://academy.langchain.com/courses/intro-to...,1,2024-09-19,Aucune
7,False,https://snap-stanford.github.io/cs224w-notes/?...,1,2024-04-24,NaN
8,False,https://stanford-cs324.github.io/winter2022/,1,2023-01-19,NaN
9,False,https://cognitiveclass.ai/,1,2023-09-28,NaN
10,False,https://hanlab.mit.edu/courses/2023-fall-65940,1,2023-09-28,NaN
11,False,https://calmcode.io/,1,2024-02-08,NaN
12,False,https://web.stanford.edu/class/cs25/index.html...,1,2023-03-02,NaN
13,False,https://tanthiamhuat.files.wordpress.com/2018/...,1,2023-04-13,NaN
14,False,https://bcourses.berkeley.edu/courses/1413454/,1,2022-09-15,NaN
15,False,https://feaz-book.com/categorical-quantile,1,2024-03-14,NaN
16,False,https://github.com/mlabonne/llm-course,5,2024-01-04,NaN
17,False,https://app.lewagon.school/collections?page=1,1,2024-02-15,NaN
18,False,https://efficientml.ai/,1,2022-09-15,NaN
19,False,https://www.youtube.com/playlist?list=PLn2-dEm...,1,2022-09-15,NaN
20,True,https://github.com/microsoft/generative-ai-for...,4,2024-10-08,Alpha Signal
21,False,https://github.com/bytedance/coconut_cvpr2024,1,2024-04-29,NaN
22,True,https://github.com/NirDiamant/GenAI_Agents,2,2024-09-25,Alpha Signal
23,False,https://github.com/KindXiaoming/pykan,1,2024-06-12,NaN
24,False,https://github.com/microsoft/graphrag,1,2024-08-08,NaN
25,False,https://github.com/igrek51/wat,1,2024-08-08,NaN
26,True,https://github.com/Sinaptik-AI/pandas-ai,0,2024-10-12,Alpha Signal
27,False,https://github.com/enjalot/latent-scope?tab=re...,1,2024-02-22,NaN
28,False,https://github.com/cxli233/FriendsDontLetFrien...,1,2024-01-25,NaN
29,True,https://github.com/Cinnamon/kotaemon,4,2024-10-15,Alpha Signal

In [47]:
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_colwidth", None)

In [52]:
pdf_snapshot.sort_values("upload_date", ascending=False).head(50)

,already_read,link,read_priority,upload_date,source
36,True,https://github.com/openai/swarm/tree/main,2,2024-10-15,Alpha Signal
29,True,https://github.com/Cinnamon/kotaemon,4,2024-10-15,Alpha Signal
55,True,https://cookbook.openai.com/examples/evaluation/how_to_eval_abstractive_summarization,0,2024-10-13,Aucune
26,True,https://github.com/Sinaptik-AI/pandas-ai,0,2024-10-12,Alpha Signal
152,True,https://www.stateof.ai/,5,2024-10-12,Alpha Signal
58,True,https://bnm3k.github.io/blog/duckdb-jit-udfs-numba,4,2024-10-12,Aucune
43,True,https://github.com/wasiahmad/Awesome-LLM-Synthetic-Data,3,2024-10-12,Alpha Signal
112,True,https://www.fharrell.com/post/cluster/?utm_source=substack&utm_medium=email,3,2024-10-12,Data science weekly
119,True,https://www.deep-ml.com/about,4,2024-10-12,Alpha Signal
128,True,https://www.government-transformation.com/data/splink-transforming-data-linking-through-open-source-collaboration,5,2024-10-09,Data Science Weekly
48,True,https://github.com/KruxAI/ragbuilder?tab=readme-ov-file#installation,4,2024-10-08,Alpha Signal
44,True,https://github.com/arcee-ai/mergekit,3,2024-10-08,Aucune
20,True,https://github.com/microsoft/generative-ai-for-beginners?tab=readme-ov-file,4,2024-10-08,Alpha Signal
56,True,https://sarahconstantin.substack.com/p/the-great-data-integration-schlep?utm_campaign=Data_Elixir&utm_source=Data_Elixir_505,4,2024-10-08,Data Elixir
165,True,https://arxiv.org/pdf/2409.18475,4,2024-10-08,Data Elixir
86,True,https://www.godaddy.com/resources/news/llm-from-the-trenches-10-lessons-learned-operationalizing-models-at-godaddy#h-1-sometimes-one-prompt-isn-t-enough,0,2024-10-07,Aucune
116,True,https://davidsj.substack.com/p/foundation?ref=blef.fr,3,2024-10-06,Bled
33,True,https://github.com/dleemiller/WordLlama,3,2024-10-02,Data Elixir
104,True,https://data-people-group.github.io/blogs/2024/09/24/docetl/?utm_campaign=Data_Elixir&utm_source=Data_Elixir_504,3,2024-10-02,Data Elixir
38,True,https://github.com/ultralytics/ultralytics,2,2024-10-01,Alpha Signal
204,True,https://mlflow.org/docs/latest/llms/llm-evaluate/index.html,0,2024-09-30,Aucune
118,True,https://www.anthropic.com/news/contextual-retrieval,3,2024-09-30,Alpha Signal
181,True,https://learn.microsoft.com/en-us/ai/playbook/technology-guidance/generative-ai/working-with-llms/evaluation/list-of-eval-metrics,5,2024-09-29,Aucune
4,True,https://github.com/anthropics/courses/tree/master/prompt_evaluations,4,2024-09-29,Aucune
82,True,https://maxhalford.github.io/blog/python-daily-cache/?ref=blef.fr,0,2024-09-28,Data Elixir
206,True,https://haystack.deepset.ai/,0,2024-09-28,Aucune
167,True,https://observablehq.com/,0,2024-09-28,Aucune
199,True,https://beam.apache.org/,3,2024-09-27,Aucune
123,True,https://readmedium.com/https://towardsdatascience.com/why-pandas-like-interfaces-are-sub-optimal-for-distributed-computing-322dacbce43,3,2024-09-25,Aucune
126,True,https://kedro.org/blog/building-scalable-data-pipelines-with-kedro-and-ibis,0,2024-09-25,Aucune
183,True,https://fugue-tutorials.readthedocs.io/index.html,0,2024-09-25,Aucune
49,True,https://github.com/run-llama/llama_parse,0,2024-09-25,Alpha Signal
22,True,https://github.com/NirDiamant/GenAI_Agents,2,2024-09-25,Alpha Signal
65,True,https://jcken95.github.io/projects/code_review.html?utm_campaign=Data_Elixir&utm_source=Data_Elixir_502,4,2024-09-24,Data Elixir
37,True,https://github.com/rio-labs/rio,0,2024-09-24,Data Elixir
46,True,https://github.com/emcf/thepipe?utm_campaign=Data_Elixir&utm_source=Data_Elixir_503#readme,0,2024-09-24,Data Elixir
125,True,https://www.answer.ai/posts/2024-09-16-rerankers.html?utm_campaign=Data_Elixir&utm_source=Data_Elixir_503,4,2024-09-24,Data Elixir
6,True,https://academy.langchain.com/courses/intro-to-langgraph,1,2024-09-19,Aucune
39,True,https://github.com/Lightning-AI/LitServe,1,2024-09-04,NaN
186,False,https://docs.coiled.io/blog/tpch.html,1,2024-09-04,NaN
145,True,https://arxiv.org/pdf/2408.14837,1,2024-09-04,Alpha signal
72,False,https://www.rungalileo.io/hallucinationindex,1,2024-08-08,NaN
25,False,https://github.com/igrek51/wat,1,2024-08-08,NaN
96,False,https://github.blog/news-insights/product-news/introducing-github-models/,1,2024-08-08,NaN
24,False,https://github.com/microsoft/graphrag,1,2024-08-08,NaN
5,False,https://carl-mcbride-ellis.github.io/TOBoML/TOBoML.pdf,1,2024-07-10,NaN
85,False,https://readmedium.com/https://towardsdatascience.com/automl-with-autogluon-transform-your-ml-workflow-with-just-four-lines-of-code-1d4b593be129,1,2024-07-10,NaN
94,False,https://readmedium.com/principal-components-analysis-pca-through-a-latent-variable-lens-2c2e5392a3a0,1,2024-07-10,NaN
111,False,https://marc.ai/probabilistic-chess.html,1,2024-07-10,NaN
117,False,https://readmedium.com/en/why-you-currently-do-not-need-deep-learning-for-time-series-forecasting-0de57f2bc0ed,1,2024-07-03,NaN

In [ ]:
pdf_snapshot.sort_values(["read_priority", "upload_date"], ascending=False).head(50)

,already_read,link,read_priority,upload_date,source
152,True,https://www.stateof.ai/,5,2024-10-12,Alpha Signal
128,True,https://www.government-transformation.com/data/splink-transforming-data-linking-through-open-source-collaboration,5,2024-10-09,Data Science Weekly
181,True,https://learn.microsoft.com/en-us/ai/playbook/technology-guidance/generative-ai/working-with-llms/evaluation/list-of-eval-metrics,5,2024-09-29,Aucune
16,False,https://github.com/mlabonne/llm-course,5,2024-01-04,NaN
29,True,https://github.com/Cinnamon/kotaemon,4,2024-10-15,Alpha Signal
58,True,https://bnm3k.github.io/blog/duckdb-jit-udfs-numba,4,2024-10-12,Aucune
119,True,https://www.deep-ml.com/about,4,2024-10-12,Alpha Signal
20,True,https://github.com/microsoft/generative-ai-for-beginners?tab=readme-ov-file,4,2024-10-08,Alpha Signal
48,True,https://github.com/KruxAI/ragbuilder?tab=readme-ov-file#installation,4,2024-10-08,Alpha Signal
56,True,https://sarahconstantin.substack.com/p/the-great-data-integration-schlep?utm_campaign=Data_Elixir&utm_source=Data_Elixir_505,4,2024-10-08,Data Elixir
165,True,https://arxiv.org/pdf/2409.18475,4,2024-10-08,Data Elixir
4,True,https://github.com/anthropics/courses/tree/master/prompt_evaluations,4,2024-09-29,Aucune
65,True,https://jcken95.github.io/projects/code_review.html?utm_campaign=Data_Elixir&utm_source=Data_Elixir_502,4,2024-09-24,Data Elixir
125,True,https://www.answer.ai/posts/2024-09-16-rerankers.html?utm_campaign=Data_Elixir&utm_source=Data_Elixir_503,4,2024-09-24,Data Elixir
43,True,https://github.com/wasiahmad/Awesome-LLM-Synthetic-Data,3,2024-10-12,Alpha Signal
112,True,https://www.fharrell.com/post/cluster/?utm_source=substack&utm_medium=email,3,2024-10-12,Data science weekly
44,True,https://github.com/arcee-ai/mergekit,3,2024-10-08,Aucune
116,True,https://davidsj.substack.com/p/foundation?ref=blef.fr,3,2024-10-06,Bled
33,True,https://github.com/dleemiller/WordLlama,3,2024-10-02,Data Elixir
104,True,https://data-people-group.github.io/blogs/2024/09/24/docetl/?utm_campaign=Data_Elixir&utm_source=Data_Elixir_504,3,2024-10-02,Data Elixir
118,True,https://www.anthropic.com/news/contextual-retrieval,3,2024-09-30,Alpha Signal
199,True,https://beam.apache.org/,3,2024-09-27,Aucune
123,True,https://readmedium.com/https://towardsdatascience.com/why-pandas-like-interfaces-are-sub-optimal-for-distributed-computing-322dacbce43,3,2024-09-25,Aucune
36,True,https://github.com/openai/swarm/tree/main,2,2024-10-15,Alpha Signal
38,True,https://github.com/ultralytics/ultralytics,2,2024-10-01,Alpha Signal
22,True,https://github.com/NirDiamant/GenAI_Agents,2,2024-09-25,Alpha Signal
6,True,https://academy.langchain.com/courses/intro-to-langgraph,1,2024-09-19,Aucune
39,True,https://github.com/Lightning-AI/LitServe,1,2024-09-04,NaN
145,True,https://arxiv.org/pdf/2408.14837,1,2024-09-04,Alpha signal
186,False,https://docs.coiled.io/blog/tpch.html,1,2024-09-04,NaN
24,False,https://github.com/microsoft/graphrag,1,2024-08-08,NaN
25,False,https://github.com/igrek51/wat,1,2024-08-08,NaN
72,False,https://www.rungalileo.io/hallucinationindex,1,2024-08-08,NaN
96,False,https://github.blog/news-insights/product-news/introducing-github-models/,1,2024-08-08,NaN
5,False,https://carl-mcbride-ellis.github.io/TOBoML/TOBoML.pdf,1,2024-07-10,NaN
85,False,https://readmedium.com/https://towardsdatascience.com/automl-with-autogluon-transform-your-ml-workflow-with-just-four-lines-of-code-1d4b593be129,1,2024-07-10,NaN
94,False,https://readmedium.com/principal-components-analysis-pca-through-a-latent-variable-lens-2c2e5392a3a0,1,2024-07-10,NaN
111,False,https://marc.ai/probabilistic-chess.html,1,2024-07-10,NaN
42,False,https://github.com/pretzelai/pretzelai,1,2024-07-03,NaN
103,False,https://www.dwarkeshpatel.com/p/francois-chollet,1,2024-07-03,NaN
117,False,https://readmedium.com/en/why-you-currently-do-not-need-deep-learning-for-time-series-forecasting-0de57f2bc0ed,1,2024-07-03,NaN
154,False,https://readmedium.com/enhancing-language-model-performance-insights-into-rag-and-chunking-augmentation-techniques-897ba15a04d6,1,2024-07-03,NaN
179,False,https://www.anthropic.com/news/claude-3-5-sonnet,1,2024-07-03,NaN
23,False,https://github.com/KindXiaoming/pykan,1,2024-06-12,NaN
32,False,https://github.com/Nixtla/nixtla/tree/main/experiments/foundation-time-series-arena,1,2024-06-12,NaN
124,False,https://www.youtube.com/playlist?list=PLw-i55H2Io6i7oaSoQSfMNGibiXtfr1Mn,1,2024-06-12,NaN
138,False,https://readmedium.com/https://medium.com/@ignacio.de.gregorio.noblejas/the-kan-revolution-arriving-at-ai-a13ff540d4e0,1,2024-06-12,NaN
69,False,https://www.oreilly.com/radar/what-we-learned-from-a-year-of-building-with-llms-part-i/?utm_source=substack&utm_medium=email,1,2024-06-05,NaN
100,False,https://realpython.com/polars-python/#dataframes-expressions-and-contexts,1,2024-06-05,NaN
133,False,https://readmedium.com/https://medium.com/cuenex/pandas-2-0-vs-polars-the-ultimate-battle-a378eb75d6d1,1,2024-06-05,NaN